INSERT INTO USERS (USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES ('test', 'test', 'a', 'b');
INSERT INTO GROUPS (NAME) VALUES ('group_a');
INSERT INTO USER_GROUPS (USER_ID, GROUP_ID) VALUES (1, 1);
